spring.datasource.url=jdbc:mysql://localhost:3306/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mysql
spring.web.error.include-stacktrace=never

spring.flyway.locations=classpath:db/migration,classpath:db/testdata

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

#spring.servlet.multipart.max-file-size=20KB

algafood.storage.tipo=local

algafood.storage.local.diretorio-fotos=C:/Users/DELL/Pictures

algafood.storage.s3.id-chave-acesso=${AWS_ACCESS_KEY_ID}
algafood.storage.s3.id-chave-acesso-secreta=${AWS_SECRET_ACCESS_KEY}
algafood.storage.s3.regiao=${AWS_REGION}
algafood.storage.s3.bucket=${AWS_BUCKET}
algafood.storage.s3.diretorio-fotos=catalogo

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${SENDGRID_APIKEY}

algafood.email.remetente=Algafood <email.testecsk@gmail.com>

algafood.email.impl=fake

